### ISSUE TITLE
unable to change views in laratab..

### ISSUE THREAD

**Issue by neoprincess** [matfish2/laratabs#1]
I've followed the instructions as indicated in the fish/laratabs page but it only loads the content of the first tab. I am getting error in command line "[Thu Feb  4 18:08:34 2016] 127.0.0.1:49858 Invalid request (Unexpected EOF)"

Please help. Thanks

**Comment by matfish2** [comment]
I suppose you mean Chrome's **console**, and not the command line. It probably has to do with the content of that specific tab, and not with a package related bug. Try to empty it temporarily and see if you still get the error.

**Comment by neoprincess** [comment]
I'm using Laravel 5.2 on an ubuntu box so I'm running php artisan serve from terminal and that is the error I get when I click on other tabs. The blades do not have anything but a single word to identify if content is displayed correctly, just the default one generated.

**Comment by matfish2** [comment]
When you view the page source do you see the content of all the tabs?
